name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run unit tests
        run: npm test
      - name: Run ESLint to fix errors
        run: npm run lint
      - name: Commit ESLint fixes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: "Bot: fix ESLint errors"
          skip_checkout: true
      - name: Run ESLint
        run: npx eslint . --ext .ts
